services:
  piston:
    image: ghcr.io/engineer-man/piston
    container_name: piston
    restart: unless-stopped
    ports:
      - "2000:2000"
    tmpfs:
      - /piston/jobs
    privileged: true
    environment:
      - PISTON_RUN_TIMEOUT=10000
      - PISTON_COMPILE_TIMEOUT=10000
      - PISTON_OUTPUT_MAX_SIZE=65536
