const fs = require('fs');
const path = require('path');

const bugs = [
  // ===== PYTHON BUGS (13) =====
  {id:1,language:"python",title:"Fix the factorial function",difficulty:"easy",
    buggy_code:"def factorial(n):\n    if n == 0:\n        return 0\n    return n * factorial(n-1)",
    correct_code:"def factorial(n):\n    if n == 0:\n        return 1\n    return n * factorial(n-1)",
    test_input:"print(factorial(5))",expected_output:"120",
    explanation:"The base case returns 0 instead of 1, making all factorial results multiply by 0."},
  {id:2,language:"python",title:"Fix the even number checker",difficulty:"easy",
    buggy_code:"def is_even(n):\n    return n % 2 != 0",
    correct_code:"def is_even(n):\n    return n % 2 == 0",
    test_input:"print(is_even(4))",expected_output:"True",
    explanation:"Uses != instead of == when checking remainder, inverting the result."},
  {id:3,language:"python",title:"Fix the list sum function",difficulty:"easy",
    buggy_code:"def sum_list(lst):\n    total = 0\n    for i in range(1, len(lst)):\n        total += lst[i]\n    return total",
    correct_code:"def sum_list(lst):\n    total = 0\n    for i in range(0, len(lst)):\n        total += lst[i]\n    return total",
    test_input:"print(sum_list([10, 20, 30, 40]))",expected_output:"100",
    explanation:"Range starts at 1 instead of 0, skipping the first element in the sum."},
  {id:4,language:"python",title:"Fix the max finder",difficulty:"easy",
    buggy_code:"def find_max(lst):\n    max_val = 0\n    for num in lst:\n        if num > max_val:\n            max_val = num\n    return max_val",
    correct_code:"def find_max(lst):\n    max_val = lst[0]\n    for num in lst:\n        if num > max_val:\n            max_val = num\n    return max_val",
    test_input:"print(find_max([-3, -7, -2, -8]))",expected_output:"-2",
    explanation:"Initializing max to 0 fails for all-negative lists since 0 is greater than every element."},
  {id:5,language:"python",title:"Fix the string reversal",difficulty:"easy",
    buggy_code:"def reverse_string(s):\n    return s[::1]",
    correct_code:"def reverse_string(s):\n    return s[::-1]",
    test_input:"print(reverse_string('hello'))",expected_output:"olleh",
    explanation:"Slice step should be -1 to reverse, not 1 which returns the original string."},
  {id:6,language:"python",title:"Fix the Fibonacci function",difficulty:"medium",
    buggy_code:"def fibonacci(n):\n    if n <= 0:\n        return 0\n    if n == 1:\n        return 1\n    a, b = 0, 1\n    for i in range(2, n + 1):\n        a, b = b, a + b\n    return a",
    correct_code:"def fibonacci(n):\n    if n <= 0:\n        return 0\n    if n == 1:\n        return 1\n    a, b = 0, 1\n    for i in range(2, n + 1):\n        a, b = b, a + b\n    return b",
    test_input:"print(fibonacci(10))",expected_output:"55",
    explanation:"Returns variable 'a' instead of 'b', giving the previous Fibonacci number."},
  {id:7,language:"python",title:"Fix the duplicate remover",difficulty:"medium",
    buggy_code:"def remove_duplicates(lst):\n    seen = []\n    result = []\n    for item in lst:\n        if item in seen:\n            result.append(item)\n        seen.append(item)\n    return result",
    correct_code:"def remove_duplicates(lst):\n    seen = []\n    result = []\n    for item in lst:\n        if item not in seen:\n            result.append(item)\n        seen.append(item)\n    return result",
    test_input:"print(remove_duplicates([1, 2, 2, 3, 4, 4, 5]))",expected_output:"[1, 2, 3, 4, 5]",
    explanation:"Condition is inverted - adds items already seen instead of items not yet seen."},
  {id:8,language:"python",title:"Fix the power calculator",difficulty:"medium",
    buggy_code:"def power(base, exp):\n    result = 1\n    for i in range(exp):\n        result += base\n    return result",
    correct_code:"def power(base, exp):\n    result = 1\n    for i in range(exp):\n        result *= base\n    return result",
    test_input:"print(power(2, 5))",expected_output:"32",
    explanation:"Uses += (addition) instead of *= (multiplication), computing base*exp+1 instead of base^exp."},
  {id:9,language:"python",title:"Fix the vowel counter",difficulty:"medium",
    buggy_code:"def count_vowels(s):\n    count = 0\n    vowels = 'aeiou'\n    for char in s:\n        if char.lower() in vowels:\n            count += 2\n    return count",
    correct_code:"def count_vowels(s):\n    count = 0\n    vowels = 'aeiou'\n    for char in s:\n        if char.lower() in vowels:\n            count += 1\n    return count",
    test_input:"print(count_vowels('Hello World'))",expected_output:"3",
    explanation:"Increments count by 2 instead of 1 for each vowel, doubling the result."},
  {id:10,language:"python",title:"Fix the average calculator",difficulty:"medium",
    buggy_code:"def average(numbers):\n    total = 0\n    for n in numbers:\n        total += n\n    return total // len(numbers)",
    correct_code:"def average(numbers):\n    total = 0\n    for n in numbers:\n        total += n\n    return total / len(numbers)",
    test_input:"print(average([10, 20, 30]))",expected_output:"20.0",
    explanation:"Uses integer division (//) instead of float division (/), truncating decimal results."},
  {id:11,language:"python",title:"Fix the binary search",difficulty:"hard",
    buggy_code:"def binary_search(arr, target):\n    low, high = 0, len(arr) - 1\n    while low < high:\n        mid = (low + high) // 2\n        if arr[mid] == target:\n            return mid\n        elif arr[mid] < target:\n            low = mid + 1\n        else:\n            high = mid - 1\n    return -1",
    correct_code:"def binary_search(arr, target):\n    low, high = 0, len(arr) - 1\n    while low <= high:\n        mid = (low + high) // 2\n        if arr[mid] == target:\n            return mid\n        elif arr[mid] < target:\n            low = mid + 1\n        else:\n            high = mid - 1\n    return -1",
    test_input:"print(binary_search([1, 3, 5, 7, 9, 11], 11))",expected_output:"5",
    explanation:"Loop condition uses < instead of <=, missing the target when low equals high."},
  {id:12,language:"python",title:"Fix the insertion sort",difficulty:"hard",
    buggy_code:"def insertion_sort(arr):\n    for i in range(1, len(arr)):\n        key = arr[i]\n        j = i - 1\n        while j >= 0 and arr[j] > key:\n            arr[j + 1] = arr[j]\n            j -= 1\n        arr[j] = key\n    return arr",
    correct_code:"def insertion_sort(arr):\n    for i in range(1, len(arr)):\n        key = arr[i]\n        j = i - 1\n        while j >= 0 and arr[j] > key:\n            arr[j + 1] = arr[j]\n            j -= 1\n        arr[j + 1] = key\n    return arr",
    test_input:"print(insertion_sort([5, 3, 8, 1, 2]))",expected_output:"[1, 2, 3, 5, 8]",
    explanation:"Places key at arr[j] instead of arr[j+1] after the while loop decrements j past the insertion point."},
  {id:13,language:"python",title:"Fix the matrix transpose",difficulty:"hard",
    buggy_code:"def transpose(matrix):\n    rows = len(matrix)\n    cols = len(matrix[0])\n    result = [[0] * rows for _ in range(cols)]\n    for i in range(rows):\n        for j in range(cols):\n            result[j][i] = matrix[j][i]\n    return result",
    correct_code:"def transpose(matrix):\n    rows = len(matrix)\n    cols = len(matrix[0])\n    result = [[0] * rows for _ in range(cols)]\n    for i in range(rows):\n        for j in range(cols):\n            result[j][i] = matrix[i][j]\n    return result",
    test_input:"print(transpose([[1, 2, 3], [4, 5, 6]]))",expected_output:"[[1, 4], [2, 5], [3, 6]]",
    explanation:"Reads from matrix[j][i] instead of matrix[i][j], failing to swap row and column indices."},

  // ===== C BUGS (12) =====
  {id:14,language:"c",title:"Fix the array sum",difficulty:"easy",
    buggy_code:"#include <stdio.h>\nint array_sum(int arr[], int n) {\n    int sum = 1;\n    for (int i = 0; i < n; i++) {\n        sum += arr[i];\n    }\n    return sum;\n}",
    correct_code:"#include <stdio.h>\nint array_sum(int arr[], int n) {\n    int sum = 0;\n    for (int i = 0; i < n; i++) {\n        sum += arr[i];\n    }\n    return sum;\n}",
    test_input:"int main() {\n    int arr[] = {1, 2, 3, 4, 5};\n    printf(\"%d\", array_sum(arr, 5));\n    return 0;\n}",
    expected_output:"15",explanation:"Sum is initialized to 1 instead of 0, adding an extra 1 to the result."},
  {id:15,language:"c",title:"Fix the average calculator",difficulty:"easy",
    buggy_code:"#include <stdio.h>\nfloat average(int arr[], int n) {\n    int sum = 0;\n    for (int i = 0; i < n; i++) {\n        sum += arr[i];\n    }\n    return sum / n;\n}",
    correct_code:"#include <stdio.h>\nfloat average(int arr[], int n) {\n    int sum = 0;\n    for (int i = 0; i < n; i++) {\n        sum += arr[i];\n    }\n    return (float)sum / n;\n}",
    test_input:"int main() {\n    int arr[] = {1, 2, 3, 4};\n    printf(\"%.1f\", average(arr, 4));\n    return 0;\n}",
    expected_output:"2.5",explanation:"Integer division truncates the decimal. Must cast to float before dividing."},
  {id:16,language:"c",title:"Fix the multiplication table",difficulty:"easy",
    buggy_code:"#include <stdio.h>\nvoid print_table(int n) {\n    for (int i = 1; i <= 5; i++) {\n        printf(\"%d \", n + i);\n    }\n}",
    correct_code:"#include <stdio.h>\nvoid print_table(int n) {\n    for (int i = 1; i <= 5; i++) {\n        printf(\"%d \", n * i);\n    }\n}",
    test_input:"int main() {\n    print_table(3);\n    return 0;\n}",
    expected_output:"3 6 9 12 15",explanation:"Uses addition (n + i) instead of multiplication (n * i) for the times table."},
  {id:17,language:"c",title:"Fix the min finder",difficulty:"easy",
    buggy_code:"#include <stdio.h>\nint find_min(int arr[], int n) {\n    int min = arr[0];\n    for (int i = 1; i < n; i++) {\n        if (arr[i] > min) {\n            min = arr[i];\n        }\n    }\n    return min;\n}",
    correct_code:"#include <stdio.h>\nint find_min(int arr[], int n) {\n    int min = arr[0];\n    for (int i = 1; i < n; i++) {\n        if (arr[i] < min) {\n            min = arr[i];\n        }\n    }\n    return min;\n}",
    test_input:"int main() {\n    int arr[] = {5, 3, 8, 1, 4};\n    printf(\"%d\", find_min(arr, 5));\n    return 0;\n}",
    expected_output:"1",explanation:"Uses > instead of < in comparison, finding maximum instead of minimum."},
  {id:18,language:"c",title:"Fix the power of two checker",difficulty:"easy",
    buggy_code:"#include <stdio.h>\nint is_power_of_two(int n) {\n    if (n <= 0) return 0;\n    while (n > 1) {\n        if (n % 2 != 0) return 0;\n        n = n / 2;\n    }\n    return 0;\n}",
    correct_code:"#include <stdio.h>\nint is_power_of_two(int n) {\n    if (n <= 0) return 0;\n    while (n > 1) {\n        if (n % 2 != 0) return 0;\n        n = n / 2;\n    }\n    return 1;\n}",
    test_input:"int main() {\n    printf(\"%d\", is_power_of_two(16));\n    return 0;\n}",
    expected_output:"1",explanation:"Returns 0 at the end instead of 1, always reporting false even for valid powers of two."},
  {id:19,language:"c",title:"Fix the bubble sort",difficulty:"medium",
    buggy_code:"#include <stdio.h>\nvoid bubble_sort(int arr[], int n) {\n    for (int i = 0; i < n - 1; i++) {\n        for (int j = 0; j < n - 1; j++) {\n            if (arr[j] > arr[j + 1]) {\n                int temp = arr[j];\n                arr[j] = arr[j + 1];\n                arr[j + 1] = arr[j];\n            }\n        }\n    }\n}",
    correct_code:"#include <stdio.h>\nvoid bubble_sort(int arr[], int n) {\n    for (int i = 0; i < n - 1; i++) {\n        for (int j = 0; j < n - 1; j++) {\n            if (arr[j] > arr[j + 1]) {\n                int temp = arr[j];\n                arr[j] = arr[j + 1];\n                arr[j + 1] = temp;\n            }\n        }\n    }\n}",
    test_input:"int main() {\n    int arr[] = {5, 3, 8, 1, 2};\n    bubble_sort(arr, 5);\n    for (int i = 0; i < 5; i++) printf(\"%d \", arr[i]);\n    return 0;\n}",
    expected_output:"1 2 3 5 8",explanation:"Swap assigns arr[j+1] = arr[j] instead of arr[j+1] = temp, breaking the swap operation."},
  {id:20,language:"c",title:"Fix the string reverse",difficulty:"medium",
    buggy_code:"#include <stdio.h>\n#include <string.h>\nvoid reverse_string(char str[]) {\n    int len = strlen(str);\n    for (int i = 0; i < len / 2; i++) {\n        char temp = str[i];\n        str[i] = str[len - i];\n        str[len - i] = temp;\n    }\n}",
    correct_code:"#include <stdio.h>\n#include <string.h>\nvoid reverse_string(char str[]) {\n    int len = strlen(str);\n    for (int i = 0; i < len / 2; i++) {\n        char temp = str[i];\n        str[i] = str[len - 1 - i];\n        str[len - 1 - i] = temp;\n    }\n}",
    test_input:"int main() {\n    char str[] = \"abcde\";\n    reverse_string(str);\n    printf(\"%s\", str);\n    return 0;\n}",
    expected_output:"edcba",explanation:"Uses index len-i instead of len-1-i, accessing the null terminator and producing wrong results."},
  {id:21,language:"c",title:"Fix the prime checker",difficulty:"medium",
    buggy_code:"#include <stdio.h>\nint is_prime(int n) {\n    if (n <= 1) return 0;\n    for (int i = 2; i * i <= n; i++) {\n        if (n % i == 0) return 1;\n    }\n    return 1;\n}",
    correct_code:"#include <stdio.h>\nint is_prime(int n) {\n    if (n <= 1) return 0;\n    for (int i = 2; i * i <= n; i++) {\n        if (n % i == 0) return 0;\n    }\n    return 1;\n}",
    test_input:"int main() {\n    printf(\"%d\", is_prime(15));\n    return 0;\n}",
    expected_output:"0",explanation:"Returns 1 when a divisor is found instead of 0, inverting the prime check logic."},
  {id:22,language:"c",title:"Fix the GCD function",difficulty:"medium",
    buggy_code:"#include <stdio.h>\nint gcd(int a, int b) {\n    while (b != 0) {\n        int temp = b;\n        b = a % b;\n        a = b;\n    }\n    return a;\n}",
    correct_code:"#include <stdio.h>\nint gcd(int a, int b) {\n    while (b != 0) {\n        int temp = b;\n        b = a % b;\n        a = temp;\n    }\n    return a;\n}",
    test_input:"int main() {\n    printf(\"%d\", gcd(48, 18));\n    return 0;\n}",
    expected_output:"6",explanation:"Assigns a = b instead of a = temp, losing the original value of b needed for the algorithm."},
  {id:23,language:"c",title:"Fix the digit counter",difficulty:"medium",
    buggy_code:"#include <stdio.h>\nint count_digits(int n) {\n    if (n == 0) return 1;\n    int count = 0;\n    if (n < 0) n = -n;\n    while (n > 0) {\n        count++;\n        n /= 100;\n    }\n    return count;\n}",
    correct_code:"#include <stdio.h>\nint count_digits(int n) {\n    if (n == 0) return 1;\n    int count = 0;\n    if (n < 0) n = -n;\n    while (n > 0) {\n        count++;\n        n /= 10;\n    }\n    return count;\n}",
    test_input:"int main() {\n    printf(\"%d\", count_digits(12345));\n    return 0;\n}",
    expected_output:"5",explanation:"Divides by 100 instead of 10, skipping digits and undercounting."},
  {id:24,language:"c",title:"Fix the binary to decimal converter",difficulty:"hard",
    buggy_code:"#include <stdio.h>\nint binary_to_decimal(int binary) {\n    int decimal = 0, base = 1;\n    while (binary > 0) {\n        int last_digit = binary % 10;\n        decimal += last_digit * base;\n        base *= 10;\n        binary /= 10;\n    }\n    return decimal;\n}",
    correct_code:"#include <stdio.h>\nint binary_to_decimal(int binary) {\n    int decimal = 0, base = 1;\n    while (binary > 0) {\n        int last_digit = binary % 10;\n        decimal += last_digit * base;\n        base *= 2;\n        binary /= 10;\n    }\n    return decimal;\n}",
    test_input:"int main() {\n    printf(\"%d\", binary_to_decimal(1101));\n    return 0;\n}",
    expected_output:"13",explanation:"Multiplies base by 10 instead of 2, treating input as decimal rather than binary."},
  {id:25,language:"c",title:"Fix the selection sort",difficulty:"hard",
    buggy_code:"#include <stdio.h>\nvoid selection_sort(int arr[], int n) {\n    for (int i = 0; i < n - 1; i++) {\n        int min_idx = i;\n        for (int j = i + 1; j < n; j++) {\n            if (arr[j] < arr[min_idx]) {\n                min_idx = j;\n            }\n        }\n        int temp = arr[i];\n        arr[i] = arr[min_idx];\n        arr[min_idx] = arr[i];\n    }\n}",
    correct_code:"#include <stdio.h>\nvoid selection_sort(int arr[], int n) {\n    for (int i = 0; i < n - 1; i++) {\n        int min_idx = i;\n        for (int j = i + 1; j < n; j++) {\n            if (arr[j] < arr[min_idx]) {\n                min_idx = j;\n            }\n        }\n        int temp = arr[i];\n        arr[i] = arr[min_idx];\n        arr[min_idx] = temp;\n    }\n}",
    test_input:"int main() {\n    int arr[] = {64, 25, 12, 22, 11};\n    selection_sort(arr, 5);\n    for (int i = 0; i < 5; i++) printf(\"%d \", arr[i]);\n    return 0;\n}",
    expected_output:"11 12 22 25 64",explanation:"Swap assigns arr[min_idx] = arr[i] instead of arr[min_idx] = temp, breaking the swap."},

  // ===== C++ BUGS (13) =====
  {id:26,language:"cpp",title:"Fix the vector sum",difficulty:"easy",
    buggy_code:"#include <iostream>\n#include <vector>\nusing namespace std;\nint vector_sum(vector<int> v) {\n    int sum = 0;\n    for (int i = 0; i <= v.size(); i++) {\n        sum += v[i];\n    }\n    return sum;\n}",
    correct_code:"#include <iostream>\n#include <vector>\nusing namespace std;\nint vector_sum(vector<int> v) {\n    int sum = 0;\n    for (int i = 0; i < v.size(); i++) {\n        sum += v[i];\n    }\n    return sum;\n}",
    test_input:"int main() {\n    vector<int> v = {1, 2, 3, 4, 5};\n    cout << vector_sum(v);\n    return 0;\n}",
    expected_output:"15",explanation:"Uses <= instead of < in loop condition, causing out-of-bounds access."},
  {id:27,language:"cpp",title:"Fix the square calculator",difficulty:"easy",
    buggy_code:"#include <iostream>\nusing namespace std;\nint square(int n) {\n    return n + n;\n}",
    correct_code:"#include <iostream>\nusing namespace std;\nint square(int n) {\n    return n * n;\n}",
    test_input:"int main() {\n    cout << square(7);\n    return 0;\n}",
    expected_output:"49",explanation:"Uses addition (n + n) instead of multiplication (n * n), computing 2n instead of n^2."},
  {id:28,language:"cpp",title:"Fix the string length counter",difficulty:"easy",
    buggy_code:"#include <iostream>\n#include <string>\nusing namespace std;\nint string_length(string s) {\n    int count = 1;\n    for (char c : s) {\n        count++;\n    }\n    return count;\n}",
    correct_code:"#include <iostream>\n#include <string>\nusing namespace std;\nint string_length(string s) {\n    int count = 0;\n    for (char c : s) {\n        count++;\n    }\n    return count;\n}",
    test_input:"int main() {\n    cout << string_length(\"hello\");\n    return 0;\n}",
    expected_output:"5",explanation:"Counter starts at 1 instead of 0, making the result always one more than actual length."},
  {id:29,language:"cpp",title:"Fix the sign checker",difficulty:"easy",
    buggy_code:"#include <iostream>\nusing namespace std;\nstring check_sign(int n) {\n    if (n > 0) return \"positive\";\n    if (n > 0) return \"negative\";\n    return \"zero\";\n}",
    correct_code:"#include <iostream>\nusing namespace std;\nstring check_sign(int n) {\n    if (n > 0) return \"positive\";\n    if (n < 0) return \"negative\";\n    return \"zero\";\n}",
    test_input:"int main() {\n    cout << check_sign(-5);\n    return 0;\n}",
    expected_output:"negative",explanation:"Second condition checks n > 0 instead of n < 0, making negatives fall through to zero."},
  {id:30,language:"cpp",title:"Fix the array copy",difficulty:"easy",
    buggy_code:"#include <iostream>\nusing namespace std;\nvoid copy_array(int src[], int dest[], int n) {\n    for (int i = 0; i < n; i++) {\n        dest[i] = src[0];\n    }\n}",
    correct_code:"#include <iostream>\nusing namespace std;\nvoid copy_array(int src[], int dest[], int n) {\n    for (int i = 0; i < n; i++) {\n        dest[i] = src[i];\n    }\n}",
    test_input:"int main() {\n    int src[] = {10, 20, 30};\n    int dest[3];\n    copy_array(src, dest, 3);\n    for (int i = 0; i < 3; i++) cout << dest[i] << \" \";\n    return 0;\n}",
    expected_output:"10 20 30",explanation:"Always copies src[0] instead of src[i], filling destination with only the first element."},
  {id:31,language:"cpp",title:"Fix the FizzBuzz",difficulty:"medium",
    buggy_code:"#include <iostream>\nusing namespace std;\nstring fizzbuzz(int n) {\n    if (n % 3 == 0 && n % 5 == 0) return \"FizzBuzz\";\n    if (n % 3 == 0) return \"Buzz\";\n    if (n % 5 == 0) return \"Fizz\";\n    return to_string(n);\n}",
    correct_code:"#include <iostream>\nusing namespace std;\nstring fizzbuzz(int n) {\n    if (n % 3 == 0 && n % 5 == 0) return \"FizzBuzz\";\n    if (n % 3 == 0) return \"Fizz\";\n    if (n % 5 == 0) return \"Buzz\";\n    return to_string(n);\n}",
    test_input:"int main() {\n    cout << fizzbuzz(9);\n    return 0;\n}",
    expected_output:"Fizz",explanation:"Fizz and Buzz labels are swapped - Fizz should be for multiples of 3, Buzz for multiples of 5."},
  {id:32,language:"cpp",title:"Fix the recursive sum",difficulty:"medium",
    buggy_code:"#include <iostream>\nusing namespace std;\nint recursive_sum(int n) {\n    if (n <= 0) return 0;\n    return n + recursive_sum(n - 2);\n}",
    correct_code:"#include <iostream>\nusing namespace std;\nint recursive_sum(int n) {\n    if (n <= 0) return 0;\n    return n + recursive_sum(n - 1);\n}",
    test_input:"int main() {\n    cout << recursive_sum(5);\n    return 0;\n}",
    expected_output:"15",explanation:"Subtracts 2 instead of 1 in the recursive call, skipping every other number."},
  {id:33,language:"cpp",title:"Fix the vowel remover",difficulty:"medium",
    buggy_code:"#include <iostream>\n#include <string>\nusing namespace std;\nstring remove_vowels(string s) {\n    string result = \"\";\n    string vowels = \"aeiou\";\n    for (char c : s) {\n        if (vowels.find(c) != string::npos) {\n            result += c;\n        }\n    }\n    return result;\n}",
    correct_code:"#include <iostream>\n#include <string>\nusing namespace std;\nstring remove_vowels(string s) {\n    string result = \"\";\n    string vowels = \"aeiou\";\n    for (char c : s) {\n        if (vowels.find(c) == string::npos) {\n            result += c;\n        }\n    }\n    return result;\n}",
    test_input:"int main() {\n    cout << remove_vowels(\"hello world\");\n    return 0;\n}",
    expected_output:"hll wrld",explanation:"Keeps vowels instead of removing them by using != instead of == in the condition."},
  {id:34,language:"cpp",title:"Fix the array rotation",difficulty:"medium",
    buggy_code:"#include <iostream>\nusing namespace std;\nvoid rotate_left(int arr[], int n) {\n    int first = arr[0];\n    for (int i = 0; i < n - 1; i++) {\n        arr[i] = arr[i + 1];\n    }\n    arr[0] = first;\n}",
    correct_code:"#include <iostream>\nusing namespace std;\nvoid rotate_left(int arr[], int n) {\n    int first = arr[0];\n    for (int i = 0; i < n - 1; i++) {\n        arr[i] = arr[i + 1];\n    }\n    arr[n - 1] = first;\n}",
    test_input:"int main() {\n    int arr[] = {1, 2, 3, 4, 5};\n    rotate_left(arr, 5);\n    for (int i = 0; i < 5; i++) cout << arr[i] << \" \";\n    return 0;\n}",
    expected_output:"2 3 4 5 1",explanation:"Places the saved first element back at index 0 instead of the last position (n-1)."},
  {id:35,language:"cpp",title:"Fix the digit sum",difficulty:"medium",
    buggy_code:"#include <iostream>\nusing namespace std;\nint digit_sum(int n) {\n    int sum = 0;\n    if (n < 0) n = -n;\n    while (n > 0) {\n        sum += n % 10;\n        n /= 100;\n    }\n    return sum;\n}",
    correct_code:"#include <iostream>\nusing namespace std;\nint digit_sum(int n) {\n    int sum = 0;\n    if (n < 0) n = -n;\n    while (n > 0) {\n        sum += n % 10;\n        n /= 10;\n    }\n    return sum;\n}",
    test_input:"int main() {\n    cout << digit_sum(1234);\n    return 0;\n}",
    expected_output:"10",explanation:"Divides by 100 instead of 10, processing only every other digit."},
  {id:36,language:"cpp",title:"Fix the merge sorted arrays",difficulty:"hard",
    buggy_code:"#include <iostream>\n#include <vector>\nusing namespace std;\nvector<int> merge_sorted(vector<int> a, vector<int> b) {\n    vector<int> result;\n    int i = 0, j = 0;\n    while (i < a.size() && j < b.size()) {\n        if (a[i] <= b[j]) result.push_back(a[i++]);\n        else result.push_back(b[j++]);\n    }\n    while (i < a.size()) result.push_back(a[i++]);\n    while (j < a.size()) result.push_back(b[j++]);\n    return result;\n}",
    correct_code:"#include <iostream>\n#include <vector>\nusing namespace std;\nvector<int> merge_sorted(vector<int> a, vector<int> b) {\n    vector<int> result;\n    int i = 0, j = 0;\n    while (i < a.size() && j < b.size()) {\n        if (a[i] <= b[j]) result.push_back(a[i++]);\n        else result.push_back(b[j++]);\n    }\n    while (i < a.size()) result.push_back(a[i++]);\n    while (j < b.size()) result.push_back(b[j++]);\n    return result;\n}",
    test_input:"int main() {\n    vector<int> a = {1, 3, 5};\n    vector<int> b = {2, 4, 6, 8};\n    vector<int> r = merge_sorted(a, b);\n    for (int x : r) cout << x << \" \";\n    return 0;\n}",
    expected_output:"1 2 3 4 5 6 8",explanation:"Last while loop checks j < a.size() instead of j < b.size(), not appending remaining elements from b."},
  {id:37,language:"cpp",title:"Fix the second largest finder",difficulty:"hard",
    buggy_code:"#include <iostream>\n#include <vector>\n#include <climits>\nusing namespace std;\nint second_largest(vector<int> v) {\n    int first = INT_MIN, second = INT_MIN;\n    for (int x : v) {\n        if (x > first) {\n            first = x;\n        } else if (x > second) {\n            second = x;\n        }\n    }\n    return second;\n}",
    correct_code:"#include <iostream>\n#include <vector>\n#include <climits>\nusing namespace std;\nint second_largest(vector<int> v) {\n    int first = INT_MIN, second = INT_MIN;\n    for (int x : v) {\n        if (x > first) {\n            second = first;\n            first = x;\n        } else if (x > second) {\n            second = x;\n        }\n    }\n    return second;\n}",
    test_input:"int main() {\n    vector<int> v = {1, 2, 3, 4, 5};\n    cout << second_largest(v);\n    return 0;\n}",
    expected_output:"4",explanation:"Missing 'second = first' before updating first, so second never captures the previous maximum."},
  {id:38,language:"cpp",title:"Fix the palindrome number check",difficulty:"hard",
    buggy_code:"#include <iostream>\nusing namespace std;\nbool is_palindrome_num(int n) {\n    if (n < 0) return false;\n    int original = n, reversed = 0;\n    while (n > 0) {\n        reversed = reversed * 10 + n % 10;\n        n /= 10;\n    }\n    return reversed != original;\n}",
    correct_code:"#include <iostream>\nusing namespace std;\nbool is_palindrome_num(int n) {\n    if (n < 0) return false;\n    int original = n, reversed = 0;\n    while (n > 0) {\n        reversed = reversed * 10 + n % 10;\n        n /= 10;\n    }\n    return reversed == original;\n}",
    test_input:"int main() {\n    cout << is_palindrome_num(12321);\n    return 0;\n}",
    expected_output:"1",explanation:"Returns reversed != original instead of reversed == original, inverting the palindrome result."},

  // ===== JAVA BUGS (12) =====
  {id:39,language:"java",title:"Fix the factorial calculator",difficulty:"easy",
    buggy_code:"public class Solution {\n    public static int factorial(int n) {\n        if (n == 0) return 0;\n        int result = 1;\n        for (int i = 1; i <= n; i++) {\n            result *= i;\n        }\n        return result;\n    }\n    public static void main(String[] args) {\n        System.out.print(factorial(5));\n    }\n}",
    correct_code:"public class Solution {\n    public static int factorial(int n) {\n        if (n == 0) return 1;\n        int result = 1;\n        for (int i = 1; i <= n; i++) {\n            result *= i;\n        }\n        return result;\n    }\n    public static void main(String[] args) {\n        System.out.print(factorial(5));\n    }\n}",
    test_input:"",expected_output:"120",explanation:"Base case returns 0 instead of 1 for factorial(0)."},
  {id:40,language:"java",title:"Fix the array reverse",difficulty:"easy",
    buggy_code:"public class Solution {\n    public static void main(String[] args) {\n        int[] arr = {1, 2, 3, 4, 5};\n        int n = arr.length;\n        for (int i = 0; i < n / 2; i++) {\n            int temp = arr[i];\n            arr[i] = arr[n - i];\n            arr[n - i] = temp;\n        }\n        for (int x : arr) System.out.print(x + \" \");\n    }\n}",
    correct_code:"public class Solution {\n    public static void main(String[] args) {\n        int[] arr = {1, 2, 3, 4, 5};\n        int n = arr.length;\n        for (int i = 0; i < n / 2; i++) {\n            int temp = arr[i];\n            arr[i] = arr[n - 1 - i];\n            arr[n - 1 - i] = temp;\n        }\n        for (int x : arr) System.out.print(x + \" \");\n    }\n}",
    test_input:"",expected_output:"5 4 3 2 1",explanation:"Uses index n-i instead of n-1-i, causing ArrayIndexOutOfBoundsException."},
  {id:41,language:"java",title:"Fix the string comparison",difficulty:"easy",
    buggy_code:"public class Solution {\n    public static void main(String[] args) {\n        String a = new String(\"hello\");\n        String b = new String(\"hello\");\n        if (a == b) {\n            System.out.print(\"equal\");\n        } else {\n            System.out.print(\"not equal\");\n        }\n    }\n}",
    correct_code:"public class Solution {\n    public static void main(String[] args) {\n        String a = new String(\"hello\");\n        String b = new String(\"hello\");\n        if (a.equals(b)) {\n            System.out.print(\"equal\");\n        } else {\n            System.out.print(\"not equal\");\n        }\n    }\n}",
    test_input:"",expected_output:"equal",explanation:"Uses == to compare String objects (reference equality) instead of .equals() for value equality."},
  {id:42,language:"java",title:"Fix the sum calculator",difficulty:"easy",
    buggy_code:"public class Solution {\n    public static int sum(int n) {\n        int total = 0;\n        for (int i = 1; i < n; i++) {\n            total += i;\n        }\n        return total;\n    }\n    public static void main(String[] args) {\n        System.out.print(sum(5));\n    }\n}",
    correct_code:"public class Solution {\n    public static int sum(int n) {\n        int total = 0;\n        for (int i = 1; i <= n; i++) {\n            total += i;\n        }\n        return total;\n    }\n    public static void main(String[] args) {\n        System.out.print(sum(5));\n    }\n}",
    test_input:"",expected_output:"15",explanation:"Loop uses < instead of <=, excluding n from the sum (computes 1+2+3+4=10 instead of 15)."},
  {id:43,language:"java",title:"Fix the absolute value",difficulty:"easy",
    buggy_code:"public class Solution {\n    public static int absVal(int n) {\n        if (n < 0) return n;\n        return n;\n    }\n    public static void main(String[] args) {\n        System.out.print(absVal(-42));\n    }\n}",
    correct_code:"public class Solution {\n    public static int absVal(int n) {\n        if (n < 0) return -n;\n        return n;\n    }\n    public static void main(String[] args) {\n        System.out.print(absVal(-42));\n    }\n}",
    test_input:"",expected_output:"42",explanation:"Returns n instead of -n when negative, failing to negate the value."},
  {id:44,language:"java",title:"Fix the palindrome checker",difficulty:"medium",
    buggy_code:"public class Solution {\n    public static boolean isPalindrome(String s) {\n        int left = 0, right = s.length();\n        while (left < right) {\n            if (s.charAt(left) != s.charAt(right)) return false;\n            left++;\n            right--;\n        }\n        return true;\n    }\n    public static void main(String[] args) {\n        System.out.print(isPalindrome(\"racecar\"));\n    }\n}",
    correct_code:"public class Solution {\n    public static boolean isPalindrome(String s) {\n        int left = 0, right = s.length() - 1;\n        while (left < right) {\n            if (s.charAt(left) != s.charAt(right)) return false;\n            left++;\n            right--;\n        }\n        return true;\n    }\n    public static void main(String[] args) {\n        System.out.print(isPalindrome(\"racecar\"));\n    }\n}",
    test_input:"",expected_output:"true",explanation:"Initializes right to s.length() instead of s.length()-1, causing StringIndexOutOfBoundsException."},
  {id:45,language:"java",title:"Fix the number reverser",difficulty:"medium",
    buggy_code:"public class Solution {\n    public static int reverse(int n) {\n        int reversed = 0;\n        while (n != 0) {\n            reversed = reversed * 10 + n % 10;\n            n %= 10;\n        }\n        return reversed;\n    }\n    public static void main(String[] args) {\n        System.out.print(reverse(1234));\n    }\n}",
    correct_code:"public class Solution {\n    public static int reverse(int n) {\n        int reversed = 0;\n        while (n != 0) {\n            reversed = reversed * 10 + n % 10;\n            n /= 10;\n        }\n        return reversed;\n    }\n    public static void main(String[] args) {\n        System.out.print(reverse(1234));\n    }\n}",
    test_input:"",expected_output:"4321",explanation:"Uses n %= 10 instead of n /= 10, creating an infinite loop instead of removing the last digit."},
  {id:46,language:"java",title:"Fix the max of three",difficulty:"medium",
    buggy_code:"public class Solution {\n    public static int maxOfThree(int a, int b, int c) {\n        if (a >= b && a >= c) return a;\n        if (b >= a && b >= c) return b;\n        return a;\n    }\n    public static void main(String[] args) {\n        System.out.print(maxOfThree(3, 7, 5));\n    }\n}",
    correct_code:"public class Solution {\n    public static int maxOfThree(int a, int b, int c) {\n        if (a >= b && a >= c) return a;\n        if (b >= a && b >= c) return b;\n        return c;\n    }\n    public static void main(String[] args) {\n        System.out.print(maxOfThree(3, 7, 5));\n    }\n}",
    test_input:"",expected_output:"7",explanation:"Returns a instead of c in the final return, never returning the third value when it is the largest."},
  {id:47,language:"java",title:"Fix the Armstrong checker",difficulty:"medium",
    buggy_code:"public class Solution {\n    public static boolean isArmstrong(int n) {\n        int original = n, sum = 0, digits = String.valueOf(n).length();\n        while (n > 0) {\n            int d = n % 10;\n            sum += Math.pow(d, digits - 1);\n            n /= 10;\n        }\n        return sum == original;\n    }\n    public static void main(String[] args) {\n        System.out.print(isArmstrong(153));\n    }\n}",
    correct_code:"public class Solution {\n    public static boolean isArmstrong(int n) {\n        int original = n, sum = 0, digits = String.valueOf(n).length();\n        while (n > 0) {\n            int d = n % 10;\n            sum += Math.pow(d, digits);\n            n /= 10;\n        }\n        return sum == original;\n    }\n    public static void main(String[] args) {\n        System.out.print(isArmstrong(153));\n    }\n}",
    test_input:"",expected_output:"true",explanation:"Uses digits-1 as the exponent instead of digits, computing the wrong power sum."},
  {id:48,language:"java",title:"Fix the switch statement",difficulty:"medium",
    buggy_code:"public class Solution {\n    public static String dayType(int day) {\n        switch (day) {\n            case 1:\n            case 2:\n            case 3:\n            case 4:\n            case 5:\n                return \"weekday\";\n            case 6:\n            case 7:\n                return \"weekday\";\n            default:\n                return \"invalid\";\n        }\n    }\n    public static void main(String[] args) {\n        System.out.print(dayType(6));\n    }\n}",
    correct_code:"public class Solution {\n    public static String dayType(int day) {\n        switch (day) {\n            case 1:\n            case 2:\n            case 3:\n            case 4:\n            case 5:\n                return \"weekday\";\n            case 6:\n            case 7:\n                return \"weekend\";\n            default:\n                return \"invalid\";\n        }\n    }\n    public static void main(String[] args) {\n        System.out.print(dayType(6));\n    }\n}",
    test_input:"",expected_output:"weekend",explanation:"Cases 6 and 7 return 'weekday' instead of 'weekend'."},
  {id:49,language:"java",title:"Fix the binary search",difficulty:"hard",
    buggy_code:"public class Solution {\n    public static int binarySearch(int[] arr, int target) {\n        int low = 0, high = arr.length - 1;\n        while (low <= high) {\n            int mid = (low + high) / 2;\n            if (arr[mid] == target) return mid;\n            else if (arr[mid] < target) low = mid;\n            else high = mid - 1;\n        }\n        return -1;\n    }\n    public static void main(String[] args) {\n        int[] arr = {1, 3, 5, 7, 9};\n        System.out.print(binarySearch(arr, 7));\n    }\n}",
    correct_code:"public class Solution {\n    public static int binarySearch(int[] arr, int target) {\n        int low = 0, high = arr.length - 1;\n        while (low <= high) {\n            int mid = (low + high) / 2;\n            if (arr[mid] == target) return mid;\n            else if (arr[mid] < target) low = mid + 1;\n            else high = mid - 1;\n        }\n        return -1;\n    }\n    public static void main(String[] args) {\n        int[] arr = {1, 3, 5, 7, 9};\n        System.out.print(binarySearch(arr, 7));\n    }\n}",
    test_input:"",expected_output:"3",explanation:"Sets low = mid instead of low = mid + 1, causing an infinite loop when target is in the upper half."},
  {id:50,language:"java",title:"Fix the matrix diagonal sum",difficulty:"hard",
    buggy_code:"public class Solution {\n    public static int diagonalSum(int[][] matrix) {\n        int n = matrix.length, sum = 0;\n        for (int i = 0; i < n; i++) {\n            sum += matrix[i][i];\n            sum += matrix[i][n - i];\n        }\n        if (n % 2 == 1) sum -= matrix[n/2][n/2];\n        return sum;\n    }\n    public static void main(String[] args) {\n        int[][] m = {{1,2,3},{4,5,6},{7,8,9}};\n        System.out.print(diagonalSum(m));\n    }\n}",
    correct_code:"public class Solution {\n    public static int diagonalSum(int[][] matrix) {\n        int n = matrix.length, sum = 0;\n        for (int i = 0; i < n; i++) {\n            sum += matrix[i][i];\n            sum += matrix[i][n - 1 - i];\n        }\n        if (n % 2 == 1) sum -= matrix[n/2][n/2];\n        return sum;\n    }\n    public static void main(String[] args) {\n        int[][] m = {{1,2,3},{4,5,6},{7,8,9}};\n        System.out.print(diagonalSum(m));\n    }\n}",
    test_input:"",expected_output:"25",explanation:"Uses n-i instead of n-1-i for anti-diagonal index, causing ArrayIndexOutOfBoundsException."}
];

fs.writeFileSync(path.join(__dirname, 'data', 'bugs.json'), JSON.stringify(bugs, null, 2));
console.log(`Generated ${bugs.length} bugs`);
console.log(`Python: ${bugs.filter(b=>b.language==='python').length}`);
console.log(`C: ${bugs.filter(b=>b.language==='c').length}`);
console.log(`C++: ${bugs.filter(b=>b.language==='cpp').length}`);
console.log(`Java: ${bugs.filter(b=>b.language==='java').length}`);
console.log(`Easy: ${bugs.filter(b=>b.difficulty==='easy').length}`);
console.log(`Medium: ${bugs.filter(b=>b.difficulty==='medium').length}`);
console.log(`Hard: ${bugs.filter(b=>b.difficulty==='hard').length}`);
